### ISSUE TITLE
TypeError: integer argument expected, got float

### ISSUE THREAD

**Issue by kosli** [paolobenve/photofloat#33]
any idea what i am doing wrong? I used the default conf-file and only changed the paths. I am running it on debian wheezy, may that be a problem due to too old version? Python 2.7.3 and php-gd is at 5.6.31

> 2017-07-23T16:07:42.112233   |--[Next level folder:]                           albums
2017-07-23T16:07:42.112586   |  |--[Next level folder:]                           2000
2017-07-23T16:07:42.127229   |  |  |--[Next level folder:]                           2000-08-12 - Bünzli 9 im Bierhübeli
2017-07-23T16:07:42.131751   |  |  |  |--[Next level folder:]                           Dima
2017-07-23T16:07:42.145290   |  |  |  |  |--[ processing image/video]                      Dsc00066b.jpg
2017-07-23T16:07:42.437353   |  |  |  |  |  |--[reducing size]                                1600
2017-07-23T16:07:42.748535   |  |  |  |  |  |--[reducing size]                                1200
2017-07-23T16:07:42.900639   |  |  |  |  |  |--[reducing size]                                800
2017-07-23T16:07:42.930821   |  |  |  |  |  |--[thumbing for albums]                          200, fit size
2017-07-23T16:07:42.960879   |  |  |  |  |  |--[thumbing for albums]                          200, square
Traceback (most recent call last):
  File "/var/www/download.kos.li/private/PhotoFloat/scanner/main.py", line 164, in <module>
    main()
  File "/var/www/download.kos.li/private/PhotoFloat/scanner/main.py", line 157, in main
    TreeWalker(Options.config['album_path'], Options.config['cache_path'])
  File "/var/www/clients/client3/web131/private/PhotoFloat/scanner/TreeWalker.py", line 28, in __init__
    folders_album = self.walk(self.album_path)
  File "/var/www/clients/client3/web131/private/PhotoFloat/scanner/TreeWalker.py", line 133, in walk
    next_walked_album = self.walk(entry)
  File "/var/www/clients/client3/web131/private/PhotoFloat/scanner/TreeWalker.py", line 133, in walk
    next_walked_album = self.walk(entry)
  File "/var/www/clients/client3/web131/private/PhotoFloat/scanner/TreeWalker.py", line 133, in walk
    next_walked_album = self.walk(entry)
  File "/var/www/clients/client3/web131/private/PhotoFloat/scanner/TreeWalker.py", line 167, in walk
    photo = Media(entry, self.cache_path)
  File "/var/www/clients/client3/web131/private/PhotoFloat/scanner/PhotoAlbum.py", line 184, in __init__
    self._photo_thumbnails(image, media_path, thumbs_path)
  File "/var/www/clients/client3/web131/private/PhotoFloat/scanner/PhotoAlbum.py", line 372, in _photo_thumbnails
    self._photo_thumbnails_cascade(image, photo_path, thumbs_path)
  File "/var/www/clients/client3/web131/private/PhotoFloat/scanner/PhotoAlbum.py", line 476, in _photo_thumbnails_cascade
    thumb = self._thumbnail(smallest_reduced_size_image, photo_path, thumbs_path, thumb_size, thumb_type)
  File "/var/www/clients/client3/web131/private/PhotoFloat/scanner/PhotoAlbum.py", line 551, in _thumbnail
    start_image_copy.thumbnail((thumb_size, thumb_size), Image.ANTIALIAS)
  File "/usr/lib/python2.7/dist-packages/PIL/Image.py", line 1562, in thumbnail
    im = self.resize(size, resample)
  File "/usr/lib/python2.7/dist-packages/PIL/Image.py", line 1298, in resize
    im = self.im.stretch(size, resample)
TypeError: integer argument expected, got float

`

**Comment by paolobenve** [comment]
I checked the type of thumb_size, it results to be an integer.

have you updated to current master?

**Comment by kosli** [comment]
i used the latest release (2.3) and added the print line, see the output below. will check now with the lastet version from master. thanks.

> 2017-07-24T00:02:58.866737   [method]                                       cascade thumbnail generation
2017-07-24T00:02:58.872881   |--[saving json options file]                     /var/www/download.kos.li/web/photofloat/options.json
2017-07-24T00:02:58.873200   |--[Next level folder:]                           albums
2017-07-24T00:02:58.968069   |  |--[Next level folder:]                           1999
2017-07-24T00:02:58.968656   |  |  |--[Next level folder:]                           1999-10-24 - Briga99
2017-07-24T00:02:58.979479   |  |  |  |--[ processing image/video]                      DCP00963.JPG
2017-07-24T00:02:59.232638   |  |  |  |  |--[reducing size]                                1600
2017-07-24T00:02:59.302537   |  |  |  |  |--[reducing size]                                1200
------  <type 'int'>
2017-07-24T00:02:59.460127   |  |  |  |  |--[reducing size]                                800
------  <type 'int'>
2017-07-24T00:02:59.490248   |  |  |  |  |--[thumbing for albums]                          200, fit size
------  <type 'int'>
2017-07-24T00:02:59.520929   |  |  |  |  |--[thumbing for albums]                          200, square
------  <type 'float'>

**Comment by kosli** [comment]
still the same when using commit d55f71733e8f328e3824974ed59bbbe15fd666ca :-(

**Comment by kosli** [comment]
haven't used python for a while, but wouldn't the round command return a float? e.g. https://github.com/paolobenve/photofloat/blob/master/scanner/PhotoAlbum.py#L546
https://docs.python.org/2/library/functions.html#round

**Comment by kosli** [comment]
extending the mentioned line with `int(round(...))` seems to fix the issue.... will see how the pictures look like.... but it will take a while for 130k pictures....

**Comment by paolobenve** [comment]
ok, fixed in master, there where more round calls without int

Thank you very much

**Comment by kosli** [comment]
thanks a lot. works now for me. at least so far, see the other new issue :-O
